# Generated by Django 5.0.6 on 2024-09-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0002_alter_history_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="diff",
        ),
        migrations.AddField(
            model_name="history",
            name="main_text_diff",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="history",
            name="memo_diff",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="history",
            name="multimedia_diff",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="history",
            name="progress_diff",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="history",
            name="todos_diff",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
