# Generated by Django 5.0.6 on 2024-09-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0003_remove_history_diff_history_main_text_diff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="level",
        ),
        migrations.AddField(
            model_name="log",
            name="detail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("VISIT", "Visit"),
                    ("LEAVE", "Leave"),
                    ("SIGNIN", "Sign In"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                ],
                default="VISIT",
                max_length=10,
            ),
        ),
    ]
