# Generated by Django 5.0.6 on 2024-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0004_remove_log_level_log_detail_alter_log_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diary",
            old_name="multimedia",
            new_name="files",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="multimedia_diff",
            new_name="files_diff",
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("VISIT", "Visit"),
                    ("LEAVE", "Leave"),
                    ("REGISTER", "Register"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                ],
                default="VISIT",
                max_length=10,
            ),
        ),
    ]
