# Generated by Django 5.0.6 on 2024-09-17 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0006_remove_diary_files_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="files_diff",
        ),
        migrations.CreateModel(
            name="FileDiff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("file_diff", models.FileField(upload_to="diary_files/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=255, unique=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_diffs",
                        to="circadian.history",
                    ),
                ),
            ],
        ),
    ]
