# Generated by Django 5.0.6 on 2024-09-17 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0007_remove_history_files_diff_filediff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filediff",
            old_name="file_name",
            new_name="file_name_diff",
        ),
        migrations.RenameField(
            model_name="filediff",
            old_name="file_type",
            new_name="file_type_diff",
        ),
        migrations.RenameField(
            model_name="filediff",
            old_name="url",
            new_name="url_diff",
        ),
    ]
