# Generated by Django 5.0.6 on 2024-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0008_rename_file_name_filediff_file_name_diff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filediff",
            name="history",
        ),
        migrations.AddField(
            model_name="diary",
            name="files",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="history",
            name="files_diff",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="FileDiff",
        ),
    ]
