# Generated by Django 5.1.1 on 2024-12-25 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circadian", "0010_remove_history_circadian_h_diary_i_80a9ed_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="type",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="diary_history_id",
            new_name="history_id",
        ),
    ]
